version: '3'
services:
  mysqldb:
    image: 'mysql:5.7'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=demo
    ports:
      - "3306:3306"
  springboot-csv-parser:
    image: springboot-csv-parser
    restart: on-failure
    ports:
      - "8082:8080"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysqldb:3306/demo?autoReconnect=true&useSSL=false"
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "root"
    build: ./
    depends_on:
      - mysqldb


